language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -f ./client/Dockerfile.dev -t jayesh0099/react-test ./client
    
script:
    - docker run -e CI=true jayesh0099/react-test npm run test
    
after_success:
    - docker build -t jayesh0099/multi-client ./client
    - docker build -t jayesh0099/multi-nginx ./nginx
    - docker build -t jayesh0099/multi-server ./server
    - docker build -t jayesh0099/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jayesh0099/multi-client
    - docker push jayesh0099/multi-nginx
    - docker push jayesh0099/multi-server
    - docker push jayesh0099/multi-worker